const CONSTANT = {
  CONFIG_TYPE: "config-type",
  CONFIG_AGE: "config-age",
  CONFIG_MENU: "config-menu",
  CATEGORY: "categogy",
  EVENT_NOT_STARTED: 1,
  EVENT_LIVE: 2,
  EVENT_FINISHED: 3,
  TRANSCODE_DOING: 0,
  TRANSCODE_SUCCESS: 1,
  TRANSCODE_ERROR: 2,
  CONTENT_TYPE_VOD: "VOD",
  CONTENT_TYPE_EVENT: "EVENT",
  CONTENT_TYPE_SERIES: "SERIES",
  CONTENT_TYPE_CHANNEL: "CHANNEL",
  CONTENT_TYPE_EMAGAZINE: "EMAGAZINE",
  ALL: -1,
  NOT_USED: 0,
  USED: 1
}

export default CONSTANT
