export { default as apiUser } from "./repository/UserRepository"
// export { default as apiCustomer } from "./repository/CustomerRepository"
export { default as apiPermission } from "./repository/PermissionCategory"
export { default as apiMedia } from "./repository/MediaRepository.js"
export { default as apiChat } from "./repository/ChatRepository"
//OnSport
export { default as apiUserOnSport } from "./repository/UserRepository"
export { default as apiChannel } from "./repository/ChannelRepository"
export { default as apiOnSportEvent } from "./repository/EventRepository"
export { default as apiRole } from "./repository/RoleRepository"
export { default as apiSlide } from "./repository/SlideRepository"
export { default as apiAdvertising } from "./repository/AdvertisingRepository"
export { default as apiLeagues } from "./repository/LeaguesRepository"
export { default as apiScreenblockOnTV } from "./repository/ScreenblockEventRepository"
export { default as apiEventTV } from "./repository/EventRepository"
export { default as apiVideosTV } from "./repository/VideoTVRepository"
export { default as apiPermissionTV } from "./repository/PermissionCategory"
export { default as apiVersion } from "./repository/VerisonRepository"
export { default as apiBanner } from "./repository/BannerRepository"
export { default as apiNotification } from "./repository/NotificationRepository"
export { default as apiBlockKeywords } from "./repository/BlockKeywords"
export { default as apiMiniGame } from "./repository/MiniGameRepository"
export { default as apiOnposrtTag } from "./repository/TagRepository"
export { default as apiTranscodes } from "./repository/TranscodesRepository"
//sub
export { default as apiIdentity } from "./repository/CustomerRepository"
export { default as apiSubscription } from "./repository/UserSubscription"
export { default as apiTicket } from "./repository/UserTicket"
export { default as apiProduct } from "./repository/UserProduct"
export { default as apiPackage } from "./repository/UserPackage"
