export { default as Table } from "./Table"
export { default as Pagination } from "./Pagination"
export { default as TitlePage } from "./TitlePage"
export { default as Modal } from "./Modal"
export { default as useStore } from "./Context"
